import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { SideBar } from './components/sidebar'
import { Header } from './components/header'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const poppins = Poppins({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'DosSantosdev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`bg-zinc-900 ${poppins.className} overflow-x-hidden antialiased`}>
        <div className="flex p-2 gap-3 flex-row  h-screen overflow-hidden ">
          <SideBar />
          <div className="flex-1 flex flex-col">
            <Header />
            <main className="min-h-0 overflow-auto scrollbar scrollbar-track-zinc-900 scrollbar-thumb-zinc-800 ">
              {children}
            </main>
          </div>
        </div>
        <ToastContainer />
      </body>
    </html>
  )
}
