import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { Header } from './components/header'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { Footer } from './components/Footer'

const poppins = Poppins({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'DosSantosdev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      className="antialiased scrollbar scrollbar-track-zinc-900 scrollbar-thumb-zinc-800"
      lang="pt-br"
    >
      <body className={`bg-zinc-900 ${poppins.className}  `}>
        <Header />
        <main className="relative top-24 mb-36 ">{children}</main>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  )
}
